DirectoryPath: /test/
HTTPHeaders:
  User-Agent: "HTMLTest"
  Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
  Accept-Language: "en-US,en;q=0.5"
  Accept-Encoding: "gzip, deflate, br"
  Connection: "keep-alive"